services:
  # Backend API
  - type: web
    name: andile-school-api
    runtime: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
    healthCheckPath: /api/health

  # Frontend
  - type: web
    name: andile-school-frontend
    runtime: static
    buildCommand: cd frontend && npm install && VITE_API_URL=$BACKEND_URL npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: andile-school-api
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
